apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: dnstest
  namespace: ops
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: dnstest
  template:
    metadata:
      labels:
        k8s-app: dnstest
  spec:
    containers:
    - name: dnstestpod
      image: opensuse/tumbleweed
      ports:
      - containerPort: 12345
      command: ["/bin/bash"]
      args: ["-c", "zypper -q install -y netcat-openbsd net-tools && hostname -A && hostname -I && grep $(hostname -i) /etc/hosts && while :; do netcat -lvp 12345; done"]
    